# Trading settings
crypto: "BTCUSD!"
order_type: "BUY"  
server: "XBTFX-MetaTrader5"

# Account details (referencing .env variables)
account_number_env: "MT5_ACCOUNT_NUMBER"
password_env: "MT5_PASSWORD"
